import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// One sidebar per learning path. Add a new key here when a new track starts.
const sidebars: SidebarsConfig = {
  express: [
    'express/index',
    {
      type: 'category',
      label: 'Lessons',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'express/lessons'}],
    },
  ],
};

export default sidebars;
